
__author__ = 'Vadim Arsenev'
__version__ = '0.9.0'
__data__ = '31.07.2021'


TEAMS = {'Manchester City': 'MCI',
         'Liverpool': 'LIV',
         'Chelsea': 'CHE',
         'Tottenham Hotspur': 'TOT',
         'Arsenal': 'ARS',
         'Manchester United': 'MUN',
         'Wolverhampton Wanderers': 'WOL',
         'Everton': 'EVE',
         'Leicester City': 'LEI',
         'West Ham United': 'WHU',
         'Watford': 'WAT',
         'Crystal Palace': 'CRY',
         'Newcastle United': 'NEW',
         'Bournemouth': 'BOU',
         'Burnley': 'BUR',
         'Southampton': 'SOU',
         'Brighton & Hove Albion': 'BHA',
         'Norwich City': 'NOR',
         'Sheffield United': 'SHU',
         'Aston Villa': 'AVL',
         'Cardiff City': 'CAR',
         'Fulham': 'FUL',
         'Huddersfield Town': 'HUD',
         'Leeds United': 'LEE',
         'West Bromwich Albion': 'WBA',
         'Derby County': 'DER',
         'Middlesbrough': 'MID',
         'Bristol City': 'BRI',
         'Nottingham Forest': 'NOF',
         'Swansea City': 'SWA',
         'Sheffield Wednesday': 'SHW',
         'Hull City': 'HUL',
         'Brentford': 'BRE',
         'Preston North End': 'PRE',
         'Blackburn Rovers': 'BLA',
         'Stoke City': 'STK',
         'Birmingham City': 'BIR',
         'Wigan Athletic': 'WIG',
         'Queens Park Rangers': 'QPR',
         'Reading': 'REA',
         'Millwall': 'MIL',
         'Luton Town': 'LUT',
         'Barnsley': 'BAR',
         'Charlton Athletic': 'CHA',
         }
